# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
 
# vi-mode
set -g mode-keys vi

# style status bar
set -g status-style "bg=#000000,fg=#cccccc"

# reload config on Ctrl-b r
bind r source-file ~/.tmux.conf
